# Generated by Django 2.2 on 2019-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_auto_20190429_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
