# Generated by Django 2.2 on 2019-04-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0003_auto_20190429_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='current',
        ),
    ]
