# Generated by Django 2.2 on 2019-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('NT', 'Northern Territory'), ('TAS', 'Tasmania')], max_length=3),
        ),
    ]
