# Generated by Django 2.2 on 2019-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('INT', 'INTERNET'), ('WAT', 'WATER'), ('ELE', 'ELECTRICITY'), ('GAS', 'GAS'), ('REN', 'RENT')], max_length=3),
        ),
    ]
