# Generated by Django 2.2 on 2019-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='postcode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='suburb',
            field=models.CharField(max_length=100),
        ),
    ]
